export const PHONE_STAGE_DESIGN_WIDTH = 375;
export const PHONE_STAGE_DESIGN_HEIGHT = 812;
export const AGE_TRACK_LEFT_PERCENT = 7.466667;
export const AGE_TRACK_WIDTH_PERCENT = 90.4;
export const AGE_TRACK_START_OFFSET_PERCENT =
    (25 / 339) * AGE_TRACK_WIDTH_PERCENT;
export const AGE_TRACK_END_OFFSET_PERCENT =
    (25 / 339) * AGE_TRACK_WIDTH_PERCENT;
export const AGE_HANDLE_TOP_PERCENT = 33.251232;
export const VIEWPORT_HEIGHT_EPSILON = 1;
export const KEYBOARD_VISUAL_VIEWPORT_GAP = 120;
